/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1', 'Initial version', _component := 'common_helpers');

/***
 *    ███████╗██╗  ██╗████████╗███████╗███╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
 *    ██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝████╗  ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
 *    █████╗   ╚███╔╝    ██║   █████╗  ██╔██╗ ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
 *    ██╔══╝   ██╔██╗    ██║   ██╔══╝  ██║╚██╗██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
 *    ███████╗██╔╝ ██╗   ██║   ███████╗██║ ╚████║███████║██║╚██████╔╝██║ ╚████║███████║
 *    ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
 *
 */

-- ENSURE PROPER EXTENSIONS

create
    extension if not exists "uuid-ossp" schema ext;
create
    extension if not exists ltree schema ext;
create
    extension if not exists unaccent schema ext;

/***
*    ██╗--██╗███████╗██╗-----██████╗-███████╗██████╗-███████╗
*    ██║--██║██╔════╝██║-----██╔══██╗██╔════╝██╔══██╗██╔════╝
*    ███████║█████╗--██║-----██████╔╝█████╗--██████╔╝███████╗
*    ██╔══██║██╔══╝--██║-----██╔═══╝-██╔══╝--██╔══██╗╚════██║
*    ██║--██║███████╗███████╗██║-----███████╗██║--██║███████║
*    ╚═╝--╚═╝╚══════╝╚══════╝╚═╝-----╚══════╝╚═╝--╚═╝╚══════╝
*    --------------------------------------------------------
*/

/***
 *     ######  ######## ########  #### ##    ##  ######
 *    ##    ##    ##    ##     ##  ##  ###   ## ##    ##
 *    ##          ##    ##     ##  ##  ####  ## ##
 *     ######     ##    ########   ##  ## ## ## ##   ####
 *          ##    ##    ##   ##    ##  ##  #### ##    ##
 *    ##    ##    ##    ##    ##   ##  ##   ### ##    ##
 *     ######     ##    ##     ## #### ##    ##  ######
 */

create or replace function helpers.is_empty_string(_text text)
    returns bool
    language sql
    immutable
    parallel safe
    cost 1
as
$$
select _text is null or _text = '';
$$;

create or replace function helpers.is_not_empty_string(_text text)
    returns bool
    language sql
    immutable
    parallel safe
    cost 1
as
$$
select not helpers.is_empty_string(_text);
$$;

create or replace function helpers.random_string(len integer default 36) returns text
    cost 1
    volatile
    language sql
as
$$
select upper(substring(md5(random()::text), 0, len + 1));
$$;

create function helpers.get_code(_text text, _separator text default '_')
    returns text
    immutable
    parallel safe
    cost 1
    language sql
as
$$
    -- removes accents (diacritic signs) from a given string --
with _unaccented as (select ext.unaccent(_text) as _title),
     -- lowercases the string
     _lowercase as (select lower(_title) as _title
                    from _unaccented),
     -- replaces anything that's not a letter, number, hyphen('-'), or underscore('_') with a hyphen('-')
     _hyphenated as (select regexp_replace(_title, '[^a-z0-9\\-_]+', _separator, 'gi') as _title
                     from _lowercase),
     -- trims hyphens('-') if they exist on the head or tail of the string
     _trimmed as (select trim(BOTH _separator FROM _title) as _title
                  from _hyphenated)
select _title
from _trimmed;

$$;

create function helpers.get_slug(_text text)
    returns text
    immutable
    parallel safe
    cost 1
    language sql
as
$$
select helpers.get_code(_text, '-');
$$;

create function helpers.unaccent_text(_text text, _lower_text bool default true) returns text
    language sql
    immutable
    parallel safe
    cost 1
as
$$
select case when _lower_text then lower(ext.unaccent(_text)) else ext.unaccent(_text) end;
$$;

/***
 *          ##  ######   #######  ##    ## ########
 *          ## ##    ## ##     ## ###   ## ##     ##
 *          ## ##       ##     ## ####  ## ##     ##
 *          ##  ######  ##     ## ## ## ## ########
 *    ##    ##       ## ##     ## ##  #### ##     ##
 *    ##    ## ##    ## ##     ## ##   ### ##     ##
 *     ######   ######   #######  ##    ## ########
 */

create function helpers.compare_jsonb_objects(_first jsonb, _second jsonb)
    returns jsonb
    immutable
    parallel safe
    cost 1
    language sql
as
$$
select json_object_agg(COALESCE(second.key, first.key), second.value)
from jsonb_each_text(_first) first
         full outer join jsonb_each_text(_second) second on first.key = second.key
where first.value is distinct from second.value;
$$;


/***
 *    ##       ######## ########  ######## ########
 *    ##          ##    ##     ## ##       ##
 *    ##          ##    ##     ## ##       ##
 *    ##          ##    ########  ######   ######
 *    ##          ##    ##   ##   ##       ##
 *    ##          ##    ##    ##  ##       ##
 *    ########    ##    ##     ## ######## ########
 */

create function helpers.ltree_parent(path ext.ltree, levels integer default 1) returns ext.ltree
    language sql
    immutable
    parallel safe
    cost 1
as
$$
    select ext.subpath(path, 0, ext.nlevel(path) - levels);
$$;

-- helpers.path_to_ltree — sanitize a separator-delimited path into an ltree.
-- Splits on _separator (default '/'), lowercases, replaces non-ltree chars
-- with '_', collapses repeated underscores, joins segments with '.'.
-- Inner dots inside a segment (e.g. "report.pdf") become part of the label,
-- not a separator.
--
-- Examples:
--   helpers.path_to_ltree('/srv/data/org-123/report.pdf')
--     -> 'srv.data.org_123.report_pdf'
--   helpers.path_to_ltree('C:\Users\Ondrej', '\')
--     -> 'c.users.ondrej'
--   helpers.path_to_ltree('com.example.module', '.')
--     -> 'com.example.module'
create function helpers.path_to_ltree(_path text, _separator text default '/')
returns ext.ltree
    immutable
    language plpgsql
as
$$
declare
    __seg text;
    __out text[] := '{}'::text[];
    __clean text;
begin
    if _path is null then
        return null;
    end if;
    if _separator is null or _separator = '' then
        raise exception 'helpers.path_to_ltree: _separator must be a non-empty string'
            using errcode = '22023';
    end if;

    foreach __seg in array string_to_array(lower(_path), _separator)
    loop
        if __seg = '' then
            continue;
        end if;
        __clean := regexp_replace(__seg, '[^a-z0-9_]', '_', 'g');
        __clean := regexp_replace(__clean, '_+', '_', 'g');
        __clean := regexp_replace(__clean, '^_+|_+$', '', 'g');
        if __clean <> '' then
            __out := __out || __clean;
        end if;
    end loop;

    if array_length(__out, 1) is null then
        return null;
    end if;

    return array_to_string(__out, '.')::ext.ltree;
end;
$$;

select *
from stop_version_update('1', _component := 'common_helpers');