/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1.3', 'Fix of jsonb normalization function', _component := 'common_helpers',
													_description := 'Text values in jsonb are being trimmed by space and quotes, quotes because of how jsonb_each works');


/***
 *    ███╗   ██╗ ██████╗ ██████╗ ███╗   ███╗ █████╗ ██╗     ██╗███████╗███████╗    ████████╗███████╗██╗  ██╗████████╗
 *    ████╗  ██║██╔═══██╗██╔══██╗████╗ ████║██╔══██╗██║     ██║╚══███╔╝██╔════╝    ╚══██╔══╝██╔════╝╚██╗██╔╝╚══██╔══╝
 *    ██╔██╗ ██║██║   ██║██████╔╝██╔████╔██║███████║██║     ██║  ███╔╝ █████╗         ██║   █████╗   ╚███╔╝    ██║
 *    ██║╚██╗██║██║   ██║██╔══██╗██║╚██╔╝██║██╔══██║██║     ██║ ███╔╝  ██╔══╝         ██║   ██╔══╝   ██╔██╗    ██║
 *    ██║ ╚████║╚██████╔╝██║  ██║██║ ╚═╝ ██║██║  ██║███████╗██║███████╗███████╗       ██║   ███████╗██╔╝ ██╗   ██║
 *    ╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚══════╝╚══════╝       ╚═╝   ╚══════╝╚═╝  ╚═╝   ╚═╝
 *
 */

create or replace function helpers.normalize_jsonb_values(_data jsonb)
	returns jsonb
	strict
	immutable
	cost 0.1
	language sql
as
$$
with normalized_values as (select key, helpers.normalize_text(value::text) normalized_value
													 from jsonb_each(_data)
													 order by key)
select jsonb_object_agg(key, trim(BOTH '" ' from normalized_value))
from normalized_values;
$$;

select *
from stop_version_update('1.3', _component := 'common_helpers');
