/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1.4', 'Fix of jsonb compare function', _component := 'common_helpers',
													_description := 'Fixed error "return type mismatch" (jsonb vs json)');
create or replace function helpers.compare_jsonb_objects(_first jsonb, _second jsonb)
    returns jsonb
    immutable
    parallel safe
    cost 1
    language sql
as
$$
select json_object_agg(COALESCE(second.key, first.key), second.value)::jsonb
from jsonb_each_text(_first) first
         full outer join jsonb_each_text(_second) second on first.key = second.key
where first.value is distinct from second.value;
$$;

select *
from stop_version_update('1.4', _component := 'common_helpers');
