/*
 GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=0&v=1&c=c&f=ANSI%20Shadow&t=STAGE%20FUNCS

 SUB GROUP HEADERS GENERATED BY: https://patorjk.com/software/taag/#p=display&h=1&v=1&c=c&f=Banner3&t=permissions

 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

select *
from start_version_update('1.5', 'Additional helper functions for permission model', _component := 'common_helpers',
                          _description := 'Missing helpers needed by permission model tables');


create or replace function helpers.get_code(_text text, _separator text DEFAULT '_'::text) returns text
    immutable
    parallel safe
    cost 1
    language sql
as
$$
    -- removes accents (diacritic signs) from a given string --
with _unaccented as (select ext.unaccent(_text) as _title),
     -- lowercases the string
     _lowercase as (select lower(_title) as _title
                    from _unaccented),
     -- replaces anything that's not a letter, number, hyphen('-'), or underscore('_') with a hyphen('-')
     _hyphenated as (select regexp_replace(_title, '[^a-z0-9\\-_]+', _separator, 'gi') as _title
                     from _lowercase),
     -- trims hyphens('-') if they exist on the head or tail of the string
     _trimmed as (select trim(BOTH _separator FROM _title) as _title
                  from _hyphenated)
select _title
from _trimmed;

$$;

create or replace function helpers.get_slug(_text text) returns text
    immutable
    parallel safe
    cost 1
    language sql
as
$$
select helpers.get_code(_text, '-');
$$;

create or replace function helpers.ltree_parent(path ext.ltree, levels integer DEFAULT 1) returns ext.ltree
    immutable
    parallel safe
    cost 1
    language sql
as
$$
    select ext.subpath(path, 0, ext.nlevel(path) - levels);
$$;

create or replace function helpers.normalize_text(_text text, _lower_text boolean DEFAULT true) returns text
    immutable
    strict
    parallel safe
    cost 1
    language sql
as
$$
select case when _lower_text then lower(ext.unaccent(_text)) else ext.unaccent(_text) end;
$$;

create or replace function helpers.trg_generate_code_from_title() returns trigger
    language plpgsql
as
$$
begin
	if new.code is null then
		new.code := helpers.get_code(new.title, '_');
	else
		new.code := helpers.get_code(new.code, '_');
	end if;

	return new;
end;
$$;


select *
from stop_version_update('1.5', _component := 'common_helpers');
