/*
 * Auth Schema Tables
 * ==================
 *
 * Core authentication/authorization tables: users, groups, permissions, tenants
 *
 * This file is part of the PostgreSQL Permissions Model v2
 * Generated from WHOLE_DB.sql
 */

set search_path = public, const, ext, stage, helpers, internal, unsecure, auth, triggers;

create table auth.provider
(
    created_at  timestamp with time zone default now()           not null,
    created_by  text                     default 'unknown'::text not null,
    updated_at  timestamp with time zone default now()           not null,
    updated_by  text                     default 'unknown'::text not null,
    provider_id integer generated always as identity
        primary key,
    code        text                 not null
        unique,
    is_active   boolean default true not null,
    allows_group_mapping boolean default false not null,
    allows_group_sync    boolean default false not null,
    constraint provider_created_by_check
        check (length(created_by) <= 250),
    constraint provider_updated_by_check
        check (length(updated_by) <= 250),
    constraint provider_sync_requires_mapping
        check ((not allows_group_sync) or (allows_group_sync and allows_group_mapping))
);

create table auth.tenant
(
    created_at       timestamp with time zone default now()           not null,
    created_by       text                     default 'unknown'::text not null,
    updated_at       timestamp with time zone default now()           not null,
    updated_by       text                     default 'unknown'::text not null,
    tenant_id        integer generated always as identity
        primary key,
    access_type_code text    default 'authenticated'::text  not null
        references const.tenant_access_type,
    uuid             uuid    default ext.uuid_generate_v4() not null,
    title            text                               not null,
    code             text                               not null,
    is_removable     boolean default true               not null,
    is_assignable    boolean default true               not null,
    is_default       boolean default false              not null,
    nrm_search_data  text,
    unique (code),
    constraint tenant_created_by_check
        check (length(created_by) <= 250),
    constraint tenant_updated_by_check
        check (length(updated_by) <= 250)
);

-- Unique index needed early for user_permission_cache FK reference
create unique index uq_tenant_uuid
    on auth.tenant (uuid);

create table auth.user_info
(
    created_at              timestamp with time zone default now()            not null,
    created_by              text                     default 'unknown'::text  not null,
    updated_at              timestamp with time zone default now()            not null,
    updated_by              text                     default 'unknown'::text  not null,
    user_id                 bigint generated by default as identity
        primary key,
    user_type_code          text    default 'normal'::text                    not null
        references const.user_type,
    last_used_provider_code text
        references auth.provider (code)
            on update set null,
    last_selected_tenant_id integer
        references auth.tenant
            on delete set null,
    code                    text    default auth.get_user_random_code()       not null
        unique,
    uuid                    uuid    default ext.uuid_generate_v4()                not null
        unique,
    can_login               boolean default true                              not null,
    username                text                                              not null
        constraint user_info_username_check
            check (length(username) <= 255),
    email                   text
        constraint user_info_email_check
            check (length(email) <= 255),
    display_name            text                                              not null
        constraint user_info_display_name_check
            check (length(display_name) <= 255),
    is_system               boolean default false                             not null,
    is_active               boolean default true                              not null,
    is_locked               boolean default false                             not null,
    original_username       text                                              not null,
    user_preferences        jsonb   default '{}'::jsonb                       not null,
    nrm_username            text generated always as (lower(username)) stored not null,
    nrm_search_data         text,
    constraint user_info_created_by_check
        check (length(created_by) <= 250),
    constraint user_info_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.tenant_user
(
    created_at     timestamp with time zone default now()           not null,
    created_by     text                     default 'unknown'::text not null,
    tenant_user_id bigint generated always as identity
        primary key,
    tenant_id      integer not null
        references auth.tenant
            on delete cascade,
    user_id        integer not null
        references auth.user_info
            on delete cascade,
    unique (tenant_id, user_id),
    constraint tenant_user_created_by_check
        check (length(created_by) <= 250)
);

create table auth.user_permission_cache
(
    created_at      timestamp with time zone default now()           not null,
    created_by      text                     default 'unknown'::text not null,
    updated_at      timestamp with time zone default now()           not null,
    updated_by      text                     default 'unknown'::text not null,
    upc_id          bigint generated always as identity
        primary key,
    user_id         bigint                      not null
        references auth.user_info
            on delete cascade,
    tenant_id       integer                     not null
        references auth.tenant,
    tenant_uuid     uuid                        not null
        references auth.tenant (uuid),
    groups              text[] default '{}'::text[] not null,
    permissions         text[] default '{}'::text[] not null,
    short_code_permissions text[] default '{}'::text[] not null,
    expiration_date     timestamp with time zone    not null,
    constraint user_permission_cache_created_by_check
        check (length(created_by) <= 250),
    constraint user_permission_cache_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.user_data
(
    created_at      timestamp with time zone default now()           not null,
    created_by      text                     default 'unknown'::text not null,
    updated_at      timestamp with time zone default now()           not null,
    updated_by      text                     default 'unknown'::text not null,
    user_data_id    bigint generated always as identity
        primary key,
    user_id         bigint not null
        unique
        references auth.user_info
            on delete cascade,
    first_name      text,
    middle_name     text,
    last_name       text,
    settings        jsonb   not null default '{}'::jsonb,
    preferences     jsonb   not null default '{}'::jsonb,
    custom_data     jsonb   not null default '{}'::jsonb,
    nrm_search_data text,
    constraint user_data_created_by_check
        check (length(created_by) <= 250),
    constraint user_data_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.user_identity
(
    created_at       timestamp with time zone default now()           not null,
    created_by       text                     default 'unknown'::text not null,
    updated_at       timestamp with time zone default now()           not null,
    updated_by       text                     default 'unknown'::text not null,
    user_identity_id bigint generated always as identity
        primary key,
    provider_code    text                 not null
        references auth.provider (code)
            on update cascade on delete cascade,
    user_id          bigint
        references auth.user_info
            on delete cascade,
    uid              text,
    provider_groups  text[],
    provider_roles   text[],
    user_data        jsonb,
    password_hash    text,
    password_salt    text,
    is_active        boolean default true  not null,
    is_verified      boolean default false not null,
    provider_oid     text                  not null
        constraint uq_user_identity_provider_oid
            unique,
    constraint user_identity_created_by_check
        check (length(created_by) <= 250),
    constraint user_identity_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.permission
(
    created_at      timestamp with time zone default now()           not null,
    created_by      text                     default 'unknown'::text not null,
    updated_at      timestamp with time zone default now()           not null,
    updated_by      text                     default 'unknown'::text not null,
    permission_id   integer generated always as identity
        primary key,
    is_assignable   boolean default true  not null,
    code            text,
    full_code       ext.ltree,
    node_path       ext.ltree,
    has_children    boolean default false not null,
    nrm_search_data text,
    short_code      text,
    source          text default null,
    constraint permission_created_by_check
        check (length(created_by) <= 250),
    constraint permission_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.perm_set
(
    created_at      timestamp with time zone default now()           not null,
    created_by      text                     default 'unknown'::text not null,
    updated_at      timestamp with time zone default now()           not null,
    updated_by      text                     default 'unknown'::text not null,
    perm_set_id     integer generated always as identity
        primary key,
    tenant_id       integer
        references auth.tenant
            on delete cascade,
    code            text                  not null,
    is_system       boolean default false not null,
    is_assignable   boolean default true  not null,
    nrm_search_data text,
    source          text default null,
    unique (code, tenant_id),
    constraint perm_set_created_by_check
        check (length(created_by) <= 250),
    constraint perm_set_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.perm_set_perm
(
    created_at    timestamp with time zone default now()           not null,
    created_by    text                     default 'unknown'::text not null,
    psp_id        integer generated always as identity
        primary key,
    perm_set_id   integer not null
        references auth.perm_set
            on delete cascade,
    permission_id integer not null
        references auth.permission
            on delete cascade,
    unique (perm_set_id, permission_id),
    constraint perm_set_perm_created_by_check
        check (length(created_by) <= 250)
);

create table auth.user_group
(
    created_at                   timestamp with time zone default now()           not null,
    created_by                   text                     default 'unknown'::text not null,
    updated_at                   timestamp with time zone default now()           not null,
    updated_by                   text                     default 'unknown'::text not null,
    user_group_id                integer generated always as identity
        primary key,
    tenant_id                    integer
        references auth.tenant,
    title                        text                  not null,
    code                         text                  not null,
    is_system                    boolean default false not null,
    is_external                  boolean default false not null,
    is_assignable                boolean default true  not null,
    is_active                    boolean default true  not null,
    is_default                   boolean default false not null,
    can_members_manage_others    boolean default false not null,
    can_members_see_others       boolean default true  not null,
    is_synced                    boolean default false not null,
    create_missing_users_on_sync boolean default false not null,
    nrm_search_data              text,
    source                       text default null,
    constraint user_group_created_by_check
        check (length(created_by) <= 250),
    constraint user_group_updated_by_check
        check (length(updated_by) <= 250),
    constraint user_group_check
        check ((is_external = false) or (is_external and (not is_default))),
    constraint must_be_external
        check ((not is_synced) or ((is_synced = true) and (is_external = true))),
    constraint must_be_synced
        check ((not create_missing_users_on_sync) or ((create_missing_users_on_sync = true) and (is_synced = true))),
    unique (code, tenant_id)
);

create table auth.user_group_mapping
(
    created_at         timestamp with time zone default now()           not null,
    created_by         text                     default 'unknown'::text not null,
    user_group_mapping_id integer generated always as identity
        primary key,
    user_group_id      integer not null
        references auth.user_group,
    provider_code      text    not null
        references auth.provider (code)
            on update cascade on delete cascade,
    mapped_object_id   text,
    mapped_object_name text,
    mapped_role        text,
    constraint user_group_mapping_created_by_check
        check (length(created_by) <= 250)
);

create table auth.owner
(
    created_at    timestamp with time zone default now()           not null,
    created_by    text                     default 'unknown'::text not null,
    owner_id      bigint generated always as identity
        primary key,
    tenant_id     integer not null
        references auth.tenant
            on delete cascade,
    user_group_id integer
        references auth.user_group
            on delete cascade,
    user_id       bigint  not null
        references auth.user_info
            on delete cascade,
    constraint owner_created_by_check
        check (length(created_by) <= 250)
);

create table auth.permission_assignment
(
    created_at    timestamp with time zone default now()           not null,
    created_by    text                     default 'unknown'::text not null,
    assignment_id bigint generated always as identity
        primary key,
    tenant_id     integer
        references auth.tenant
            on delete cascade,
    user_group_id integer
        references auth.user_group,
    user_id       bigint
        references auth.user_info,
    perm_set_id   integer
        references auth.perm_set,
    permission_id integer
        references auth.permission,
    constraint permission_assignment_created_by_check
        check (length(created_by) <= 250),
    constraint pa_either_object
        check ((user_group_id is not null) or (user_id is not null)),
    constraint pa_either_perm
        check ((perm_set_id is not null) or (permission_id is not null))
);

create table auth.user_event
(
    created_at         timestamp with time zone default now()           not null,
    created_by         text                     default 'unknown'::text not null,
    correlation_id     text,
    user_event_id      bigint generated always as identity,
    event_type_code    text not null,
    requester_user_id  bigint
        references auth.user_info
            on delete set null,
    target_user_id     bigint
        references auth.user_info
            on delete set null,
    requester_username text,
    target_user_oid    text,
    target_username    text,
    request_context    jsonb,
    event_data         jsonb,
    constraint user_event_created_by_check
        check (length(created_by) <= 250),
    primary key (user_event_id, created_at)
) partition by range (created_at);

create table auth.token
(
    created_at         timestamp with time zone default now()           not null,
    created_by         text                     default 'unknown'::text not null,
    updated_at         timestamp with time zone default now()           not null,
    updated_by         text                     default 'unknown'::text not null,
    token_id           bigint generated always as identity
        primary key,
    user_id            bigint
        references auth.user_info,
    user_event_id      integer, -- logical FK to auth.user_event (not enforced: partitioned table requires partition key in FK target)
    token_state_code   text default 'valid'::text             not null
        references const.token_state,
    token_type_code    text                                   not null
        references const.token_type,
    token_channel_code text                                   not null
        references const.token_channel,
    user_oid           text,
    uid                text default helpers.random_string(12) not null
        unique,
    token              text                                   not null,
    expires_at         timestamp with time zone               not null,
    used_at            timestamp with time zone,
    request_context    jsonb,
    token_data         jsonb,
    constraint token_created_by_check
        check (length(created_by) <= 250),
    constraint token_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.api_key
(
    created_at         timestamp with time zone default now()           not null,
    created_by         text                     default 'unknown'::text not null,
    updated_at         timestamp with time zone default now()           not null,
    updated_by         text                     default 'unknown'::text not null,
    api_key_id         integer generated always as identity
        primary key,
    tenant_id          integer default 1 not null
        references auth.tenant
            on delete cascade,
    title              text              not null,
    description        text,
    api_key            text              not null
        unique,
    -- Inbound key fields (for validating incoming requests)
    secret_hash        bytea,
    -- Outbound key fields (for calling external services)
    key_type           text              not null default 'inbound'
        check (key_type in ('inbound', 'outbound')),
    encrypted_secret   bytea,            -- Pre-encrypted by application layer
    service_code       text,             -- e.g., 'sendgrid', 'slack', 'azure_storage'
    service_url        text,             -- e.g., 'https://api.sendgrid.com'
    extra_data         jsonb,            -- Extra headers, config, etc.
    -- Common fields
    expire_at          timestamp with time zone,
    notification_email text,
    nrm_search_data    text,
    constraint api_key_created_by_check
        check (length(created_by) <= 250),
    constraint api_key_updated_by_check
        check (length(updated_by) <= 250),
    -- Ensure proper secret storage based on key type
    constraint api_key_type_secret_check
        check (
            (key_type = 'inbound' and secret_hash is not null) or
            (key_type = 'outbound' and encrypted_secret is not null)
        ),
    -- Service code required for outbound keys
    constraint api_key_outbound_service_check
        check (key_type = 'inbound' or service_code is not null)
);

create table auth.user_group_member
(
    created_at       timestamp with time zone default now()           not null,
    created_by       text                     default 'unknown'::text not null,
    member_id        bigint generated always as identity
        primary key,
    user_group_id    integer                     not null
        references auth.user_group
            on delete cascade,
    user_id          bigint                      not null
        references auth.user_info
            on delete cascade,
    mapping_id       integer
        references auth.user_group_mapping
            on delete cascade,
    member_type_code text default 'manual'::text not null
        references const.user_group_member_type
            on delete cascade,
    constraint user_group_member_created_by_check
        check (length(created_by) <= 250)
);

create table auth.user_tenant_preference
(
    created_at                timestamp with time zone default now()           not null,
    created_by                text                     default 'unknown'::text not null,
    updated_at                timestamp with time zone default now()           not null,
    updated_by                text                     default 'unknown'::text not null,
    tenant_user_preference_id bigint generated always as identity
        primary key,
    user_id                   bigint                    not null
        references auth.user_info
            on delete cascade,
    tenant_id                 bigint                    not null
        references auth.tenant
            on delete cascade,
    user_preferences          jsonb default '{}'::jsonb not null,
    constraint user_tenant_preference_created_by_check
        check (length(created_by) <= 250),
    constraint user_tenant_preference_updated_by_check
        check (length(updated_by) <= 250)
);

create table auth.user_blacklist
(
    created_at        timestamptz default now() not null,
    created_by        text default 'unknown'::text not null
        constraint user_blacklist_created_by_check check (length(created_by) <= 250),
    blacklist_id      bigint generated always as identity primary key,
    username          text,
    provider_code     text references auth.provider (code) on update cascade on delete cascade,
    provider_uid      text,
    provider_oid      text,
    original_user_id  bigint,
    reason            text,
    notes             text,
    constraint user_blacklist_has_identity
        check (username is not null or provider_uid is not null or provider_oid is not null)
);

create unique index uq_auth_user_info
    on auth.user_info (username);

create index ix_trgm_user_info_search
    on auth.user_info using gin (nrm_search_data ext.gin_trgm_ops);

create unique index uq_user_permission_cache
    on auth.user_permission_cache (user_id, tenant_id);

create index ix_trgm_user_data_search
    on auth.user_data using gin (nrm_search_data ext.gin_trgm_ops);

create unique index uq_user_identity
    on auth.user_identity (provider_code, coalesce(uid, '-1'::text));

create unique index uq_permission_full_code
    on auth.permission (full_code);

create index ix_permission_node_path
    on auth.permission using gist (node_path);

create unique index uq_permission_short_code
    on auth.permission (short_code) where short_code is not null;

create unique index uq_user_group_mapping
    on auth.user_group_mapping (user_group_id, provider_code, coalesce(mapped_object_id, ''::text), coalesce(mapped_role, ''::text));

create unique index ix_owner
    on auth.owner (user_id, tenant_id, user_group_id);

create unique index uq_permission_assignment
    on auth.permission_assignment (user_group_id, coalesce(user_id, 0::bigint), coalesce(perm_set_id, 0), coalesce(permission_id, 0));

create unique index uq_auth_permission_assignment_tenant_user
    on auth.permission_assignment (tenant_id, user_id, coalesce(perm_set_id, 0), coalesce(permission_id, 0));

create unique index uq_auth_permission_assignment_tenant_group
    on auth.permission_assignment (tenant_id, user_group_id, coalesce(perm_set_id, 0), coalesce(permission_id, 0));

create index ix_user_event_data
    on auth.user_event using gin (event_data jsonb_path_ops);

create index ix_user_event_correlation_id
    on auth.user_event(correlation_id) where correlation_id is not null;

create index ix_user_event_created
    on auth.user_event (created_at desc);

create index ix_user_event_target_user
    on auth.user_event (target_user_id, created_at desc);

create index ix_user_event_request_context
    on auth.user_event using gin (request_context) where request_context is not null;

create index ix_blacklist_username
    on auth.user_blacklist (username) where username is not null;

create index ix_blacklist_provider_uid
    on auth.user_blacklist (provider_code, provider_uid) where provider_code is not null and provider_uid is not null;

create index ix_blacklist_provider_oid
    on auth.user_blacklist (provider_oid) where provider_oid is not null;

-- Default partition (safety net for unexpected created_at values)
create table auth.user_event_default partition of auth.user_event default;

-- Create initial monthly partitions for user_event
do $$
declare
    __start date;
    __end date;
    __partition_name text;
    __i integer;
begin
    for __i in -1..3 loop
        __start := date_trunc('month', now()) + make_interval(months => __i);
        __end := __start + interval '1 month';
        __partition_name := 'user_event_' || to_char(__start, 'YYYY_MM');

        if not exists (
            select 1 from pg_class c
            join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'auth' and c.relname = __partition_name
        ) then
            execute format(
                'create table auth.%I partition of auth.user_event for values from (%L) to (%L)',
                __partition_name, __start, __end
            );
        end if;
    end loop;
end $$;

create index ix_token_token
    on auth.token using hash (token);

create index ix_token_expires_at
    on auth.token (expires_at);

create index ix_token_token_data
    on auth.token using gin (token_data jsonb_path_ops);

create unique index uq_user_group_member
    on auth.user_group_member (user_group_id, user_id, coalesce(mapping_id, 0));

create unique index uq_user_tenant_preference
    on auth.user_tenant_preference (user_id, tenant_id);

-- Search indexes for nrm_search_data columns
create index ix_trgm_tenant_search
    on auth.tenant using gin (nrm_search_data ext.gin_trgm_ops);

create index ix_trgm_user_group_search
    on auth.user_group using gin (nrm_search_data ext.gin_trgm_ops);

create index ix_trgm_permission_search
    on auth.permission using gin (nrm_search_data ext.gin_trgm_ops);

create index ix_trgm_perm_set_search
    on auth.perm_set using gin (nrm_search_data ext.gin_trgm_ops);

create index ix_trgm_api_key_search
    on auth.api_key using gin (nrm_search_data ext.gin_trgm_ops);

